config/routes.rb
Trackr::Application.routes.draw do

  get "friends/index"

  resources :goal_instances do
    put :check, on: :member
    put :cheeron, on: :member
  end
  

  get "login/index"

  get "login/callback"
  
  get "login/perf_login", :to=>"login#perf_login"

  resources :goals

  resources :users
 
  get "logout" => "login#destroy", :as => "logout"

  root :to => 'login#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  has_many :goal_instances
  belongs_to :user
  has_attached_file :picture
  validates :title, presence: true
  validates_attachment_content_type :picture, :content_type => ["image/jpeg","image/png"]
  attr_accessible :description, :title, :user, :picture, :goal_instances
  
  
  before_update :ensure_no_followers
  before_destroy :ensure_no_followers
  
   
  private
    def ensure_no_followers
      #check goal instance table to check if there are any current users
      current_users_exist = false
      goal_instances.each {|goal_instance|
        if !goal_instance.is_complete
          return false
        end
      }
      return true
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authorize, only: [:update, :destroy]
  cache_sweeper :goals_sweeper, :only => [:create, :update, :destroy]
  caches_action :index, :expires_in => 30.minutes,  :cache_path => Proc.new { |c| c.params } # index_cache_path.to_proc
  
  
  # GET /goals
  # GET /goals.json
  def index
    #@goals = Goal.all
    if(params[:search])
      search = params[:search]
      #cache ["goals",@goals] do
      @goals = Goal.paginate(:page => params[:page], 
                              :per_page => 12,
                              :conditions => ['title like ?', 
                              "%#{search}%"], 
                              :order => 'title')
      #end
    else
      @goals = Goal.paginate(:page => params[:page], 
                              :per_page => 12, 
                              :order => 'title')
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  
  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = Goal.find(params[:id])
    @api = Koala::Facebook::API.new(session[:access_token])
    @is_current_user_joined = false
    _user_ids = @goal.goal_instances.pluck(:user_id)
    _users = User.where('id in (?)',_user_ids).pluck(:fb_id)
    _current_follower_ids = _users
    @is_current_user_joined = _user_ids.include? session[:current_user]
    puts "current user joined. ........................."+ @is_current_user_joined.to_s
    if _current_follower_ids.length > 0
      @current_followers= @api.get_objects(_current_follower_ids, :fields=>"first_name,last_name,picture")
      if @current_followers.length > 0 then
        @current_followers = @current_followers.values
      end
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/new
  # GET /goals/new.json
  def new
    @goal = Goal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/1/edit
  def edit
    @goal = Goal.find(params[:id])
  end

  # POST /goals.json
  def create
    # expire_action :action => :index
    # cache_key = "views/tmp/cache/goals"
    # Rails.cache.delete(cache_key)

    @goal = Goal.new(params[:goal])
    current_user = User.find(session[:current_user])
    current_user.goals.push(@goal)
    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render json: @goal, status: :created, location: @goal }
      else
        format.html { render action: "new" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goals/1
  # PUT /goals/1.json
  def update
    # expire_action :action => :index
    # cache_key = "views/tmp/cache/goals"
    # Rails.cache.delete(cache_key)

    @goal = Goal.find(params[:id])

    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    # expire_action :action => :index
    # cache_key = "views/tmp/cache/goals"
    # Rails.cache.delete(cache_key)

    @goal = Goal.find(params[:id])
      respond_to do |format|
        if !@goal.destroy
          format.html {redirect_to @goal , notice: "You may not edit or delete this goal. There are users currently following it."}
          format.json {head :no_content}
        else
          format.html { redirect_to goals_url }
          format.json { head :no_content }
        end 
      end
    
  end
  
  private
    def authorize
      @goal = Goal.find(params[:id])
        #unless @goal.user.id == session[:current_user]
         # redirect_to @goal , notice: 'You are not authorized to execute this action'
      #end
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
	 <% if @goal.errors.any? %>
		<div class="alert alert-danger" >
  			<button type="button" class="close" data-dismiss="alert">&times;</button>
  			<h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

			<ul>
			<% @goal.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
			</ul>
  		</div>
	<% end %>

	<div class="media">
		<div class="pull-left">
			<a href="#">
				<%= image_tag @goal.picture.url, :class => "img-thumbnail img-responsive", :width => "350px", :height => "350px" %>
			</a>
			<br />
			<span class="btn btn-file"><%= f.label "Change Image" %><br />
		  	<%= f.file_field :picture %><i class="glyphicon glyphicon-picture"></i></span>
			<!-- <a data-toggle="modal" href="#modal_window" class="btn btn-default navbar-btn" style="margin-left:100px;">
				Change Image <i class="glyphicon glyphicon-picture"></i>
			</a> -->
		</div>
		
		<div class="pull-right col-sm-7">
		  <div class="form-group">
		    <h4><span class="label label-primary"><%= f.label :title %></span></h4>
		    <%= f.text_area :title, rows:1, :class => "form-control"%>
		  </div>

		  <div class="form-group">
		    <h4><span class="label label-primary"><%= f.label :description %></span></h4>
		    <%= f.text_area :description, rows:7, :class => "form-control" %>
		  </div>
		  
		  <%= link_to raw('<i class="glyphicon glyphicon-chevron-left"></i> Back'), goals_path, :class => "btn btn-primary" %>
		  <%= f.submit "Create New Goal", :class => "btn btn-success navbar-btn" %>
		</div>
	</div>

	<!-- modal window start-->
	<div id="modal_window" class="modal fade in">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Select file</h3>
	</div>
	<div class="modal-body">
		<div class="field">
		  <%= f.label :picture %><br />
		  <%= f.file_field :picture %>
		</div>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
	</div>
	<!-- modal window end -->
  </div>
<% end %>

app/views/goals/_form_edit.html.erb
	<%= form_for(@goal) do |f| %>
	<% if @goal.errors.any? %>
		<div class="alert alert-danger" >
  			<button type="button" class="close" data-dismiss="alert">&times;</button>
  			<h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

			<ul>
			<% @goal.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
			</ul>
  		</div>
	<% end %>


	<div class="media">
		<div class="pull-left">
			<a href="#">
				<%= image_tag @goal.picture.url, :class => "img-thumbnail img-responsive", :width => "350px", :height => "350px" %>
			</a>
			<br />
			<span class="btn btn-file"><%= f.label "Change Image" %><br />
		  	<%= f.file_field :picture %><i class="glyphicon glyphicon-picture"></i></span>
			<!-- <a data-toggle="modal" href="#modal_window" class="btn btn-default navbar-btn" style="margin-left:100px;">
				Change Image <i class="glyphicon glyphicon-picture"></i>
			</a> -->
		</div>
		
		<div class="pull-right col-sm-7">
		  <div class="form-group">
		    <h4><span class="label label-primary"><%= f.label :title %></span></h4>
		    <%= f.text_area :title, rows:1, :class => "form-control"%>
		  </div>

		  <div class="form-group">
		    <h4><span class="label label-primary"><%= f.label :description %></span></h4>
		    <%= f.text_area :description, rows:7, :class => "form-control" %>
		  </div>

		 
		  <%= link_to raw('Cancel <i class="glyphicon glyphicon-remove-circle"></i>'), goals_path, :class => "btn btn-primary" %>
		  <%= f.submit 'Update Goal', :class => "btn btn-success navbar-btn" %>
		</div>
	</div>
	<!-- modal window start-->
	<div id="modal_window" class="modal fade in">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Select file</h3>
	</div>
	<div class="modal-body">
		<div class="field">
		  <%= f.label :picture %><br />
		  <%= f.file_field :picture %>
		</div>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
	</div>
	<!-- modal window end -->
<% end %>

app/views/goals/edit.html.erb
<div class="container">
	<div class="panel panel-default">
	    <div class="panel-heading">
			<div class="panel-title text-center">
			<b><i class="glyphicon glyphicon-edit"></i> Edit the Goal</b>
			</div>
		</div>
		<div class="panel-body">
			<%= render 'form_edit' %>
		</div>
	</div>
</div>
	

app/views/goals/index.html.erb
<div class="container container-g">

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
	

<form role="search" action=<%=request.path%>>
<div class="col-lg-6">
    <div class="input-group">
      <input name="search" type="text" class="form-control" placeholder="Search Goals...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Search <i class="glyphicon glyphicon-search"></i></button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</form>
<%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Create New Goal'), new_goal_path, :class => "btn btn-primary" %>

<br />
<br />

<% @goals.each_with_index do |goal,index| %>
  <% if (index+1) % 3 == 0 %>
  	<div class="row">
  <%end%>

  <div class="col-sm-12 col-md-4">
  	<div class="thumbnail">
  	  	<%= image_tag goal.picture.url, :width => "300px", :height => "300px" %>
  	  	<div class="caption" >
  	  		<h4 class="text-center">
          <%= link_to goal.title, goal%>
          <span class="badge"><%= goal.goal_instances.length%> <i class="glyphicon glyphicon-fire" ></i></span>

          </h4>
  	  	</div>
     </div>
  </div>

  <% if (index+1) % 3 == 0 %>
  	</div>
  <%end%>
<% end %>
	
<br />
<%= will_paginate @goals,renderer: BootstrapPagination::Rails%>
</div>

app/views/goals/new.html.erb
<div class="container">
	<div class="panel panel-default">
	    <div class="panel-heading">
			<div class="panel-title text-center">
			<b><i class="glyphicon glyphicon-plus"></i> Create a New Goal</b>
			</div>
		</div>
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/goals/show.html.erb
<div class="container">

<% if notice %>
<div class="alert alert-success" >
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<%= notice %>
</div>
<% end %>

<div class="container">
	<div class="pull-left" style="margin: 20px 20px 0px 0px;">
		<a href="#">
			<%= image_tag @goal.picture.url, :class => "img-thumbnail img-responsive", :width => "350px", :height => "350x" %>
		</a>
	</div>
	
	<div class="container">
		<div class="pull-right" style="margin-top:10px;">
			<% if !@is_current_user_joined %>
				<%= link_to raw('Join <i class="glyphicon glyphicon-share-alt"></i>'), new_goal_instance_path(:goal_id => @goal.id), :class => "btn btn-lg btn-success"%>
			<%end%>
		</div>
		<h1><b><%= @goal.title %></b></h1>
			
		<hr />
		<h2><small><%= @goal.description %></small></h2>
		
		<%if @goal.user then %>
			<hr />
			<div class="text-center"><h4>
				Created by 
				<%= link_to @goal.user.first_name + " " + @goal.user.last_name,
						{:controller => "goal_instances", :user_id => @goal.user.id}
				%>
			</h4></div>
		<%end%> 
	</div>	


<% if @current_followers and @current_followers.length != 0%>
	<!-- carousel -->
	<br/>
	<br/>
	<% number_loops = @current_followers.length / 6
	   if ( @current_followers.length % 6 != 0 )
	   		number_loops= number_loops+ 1
	   end
	%>
	
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
	  <ol class="carousel-indicators">
	  	<% for i in 0..number_loops-1%>
	    	<li data-target="#myCarousel" data-slide-to="<%=i%>"></li>
	    <% end %>
	  </ol>
	  
	  
	  <div class="carousel-inner">
	  	<% for i in 0..number_loops-1%>
	    <div class="item  <%if i == 0 then%> active <%end%>" >
	      	<img width="100%" src="/assets/blue-001.jpg"></img>

	      	<div class="container">

		        <div class="carousel-caption">
		          
		          <h3 style="text-shadow: 0 0 0.5em black;">Currently Pursuing : <%=@current_followers.length%>  Followers</h3>
				  <div class="row">
				  	<%for j in 0..5%>
				  		<% index = i*6 + j %>
				  		<% if @current_followers[index] then %>
				  		<div class="col-md-2" style="margin-p"> 
				  			<img width="100%" height="100%" src=<%=@current_followers[index]["picture"]["data"]["url"]%> />
				  			
				  			<br />
				  			
				  			<% if (str = @current_followers[index]["first_name"].to_s.split(' ')).length > 1%>
				  				<% if str[0].length < 8 %>
				  					<%= str[0] + ' ' + str[1].first + '.' %>
				  				<% else %>
				  					<%= str.last%>
				  				<% end %>
				  			<% else %>
				  				<%= @current_followers[index]["first_name"]%> 
				  			<% end %>
				  			
				  			<br/> 

				  			<% if (str = @current_followers[index]["last_name"].to_s.split(' ')).length > 1%>
				  				<% if str.last.length < 8 %>
				  					<%= str[0].first + '. ' + str.last %>
				  				<% else %>
				  					<%= str.last%>
				  				<% end %>
				  			<% else %>
				  				<%= @current_followers[index]["last_name"]%> 
				  			<% end %>
				  		</div>
				  		<%end%>
				  	<%end%>
				  </div>
			    </div>
		    </div>
	    </div>
	    <% end %>
	  </div>
	  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
	  <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
	</div>
	<!-- end of carousel-->
<%end%>
<br />

<%= link_to raw('<i class="glyphicon glyphicon-chevron-left"></i> Back'), goals_path, :class => "btn btn-default" %>
<% if @goal.user %>
	<% if @goal.user.id == session[:current_user] %>
		<%= link_to(raw('<i class="glyphicon glyphicon-edit"></i> Edit'), edit_goal_path(@goal), {:class => "btn btn-primary"}) %>
	<%end%>
<%end%>

<span style="float:right;">
<% if @goal.user and @goal.user.id == session[:current_user] %>
	<%= button_to 'Delete', @goal, method: :delete, confirm: "Do you really want to delete this goal ?" , :class => "btn btn-default" %>
<%end%>

</div>