config/routes.rb
Trackr::Application.routes.draw do

  get "friends/index"

  resources :goal_instances do
    put :check, on: :member
    put :cheeron, on: :member
  end
  

  get "login/index"

  get "login/callback"
  
  get "login/perf_login", :to=>"login#perf_login"

  resources :goals

  resources :users
 
  get "logout" => "login#destroy", :as => "logout"

  root :to => 'login#index'

end

app/models/goal_instance.rb
class GoalInstance < ActiveRecord::Base
  belongs_to :user, touch: true
  belongs_to :goal, touch: true
  has_many :milestones
  attr_accessible :cheer_ons, :end_date, :is_complete, :start_date, :user, :goal, :goal_id, :milestones, :milestones_attributes
  accepts_nested_attributes_for :milestones, :limit => 3, :reject_if => lambda { |a| a[:description].blank? }, :allow_destroy => true
end

app/controllers/goal_instances_controller.rb
class GoalInstancesController < ApplicationController
  cache_sweeper :goal_instances_sweeper, :only => [:create, :update, :destroy]
  caches_action :index, :expires_in => 30.minutes,  :cache_path => Proc.new { |c| c.params } # index_cache_path.to_proc

  # GET /goal_instances
  # GET /goal_instances.json
  def index
    puts 'params[:user_id] = ' + params[:user_id].inspect
    if params[:user_id] == nil
      current_user = User.find(session[:current_user])
    else
      current_user = User.find(params[:user_id])
    end
    
    @goal_instances = current_user.goal_instances
    @goal_instances = @goal_instances.paginate(:page => params[:page], :per_page => 5)
    @milestones = Milestone.find_by_goal_instance_id(params[:id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:goal_instances => @goal_instances, :milestones => @milestones}}
    end
  end

  # GET /goal_instances/1
  # GET /goal_instances/1.json
  def show

    @goal_instance = GoalInstance.find(params[:id])
    @is_current_user_joined = false
    goal_ins = GoalInstance.where('user_id = :uid and goal_id = :gid', 
                  {uid: session[:current_user], gid: @goal_instance.goal.id})
    puts 'goal_ins = ' + goal_ins.to_s
    puts 'goal_ins.length = ' + goal_ins.length.to_s

    if goal_ins.length > 0
      @is_current_user_joined = true;
    end

    @milestones = @goal_instance.milestones

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: {:goal_instances => @goal_instances, :milestones => @milestones}}
   end
end

def update_preview
  puts "-> hey!!!"
end

#def completed
# @goal_instan = GoalInstance.find(params[:goal_instance_id])
# @milesto = @goal_instan.milestones.find([params[:id])
#  respond_to do |format|
#  format.js { render :nothing => true }
#  format.html redirect_to(@goal_instan)
#end
 

  # GET /goal_instances/new
  # GET /goal_instances/new.json
  def new
    @goal_instance = GoalInstance.new
    3.times{ @goal_instance.milestones.build }
    puts params[:goal_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goal_instance }
    end
  end

  # GET /goal_instances/1/edit
  def edit
    @goal_instance = GoalInstance.find(params[:id])
  end
   

  # POST /goal_instances
  # POST /goal_instances.json
  def create
    puts params.to_s()
    @goal_instance = GoalInstance.new(params[:goal_instance])
    current_user = User.find(session[:current_user])
    current_user.goal_instances.push(@goal_instance)
    puts params[:goal_instance][:goal_id]
    current_goal = Goal.find(params[:goal_instance][:goal_id]) 
    current_goal.goal_instances.push(@goal_instance)
    respond_to do |format|
      if @goal_instance.save
        format.html { redirect_to @goal_instance, notice: 'Goal instance was successfully created.' }
        format.json { render json: @goal_instance, status: :created, location: @goal_instance }
      else
        format.html { render action: "new" }
        format.json { render json: @goal_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goal_instances/1
  # PUT /goal_instances/1.json
  def update
    @goal_instance = GoalInstance.find(params[:id])

    respond_to do |format|
      if @goal_instance.update_attributes(params[:goal_instance])
        format.html { redirect_to @goal_instance, notice: 'Goal instance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goal_instances/1
  # DELETE /goal_instances/1.json
  def destroy
    @goal_instance = GoalInstance.find(params[:id])
    @goal_instance.destroy

    respond_to do |format|
      format.html { redirect_to goal_instances_url(:user_id => User.find(session[:current_user]).id) }
      format.json { head :no_content }
    end
  end

  # PUT /goal_instances/1/cheeron
  def cheeron
    puts 'Cheeron ajax'
    @goal_instance = GoalInstance.find(params[:id])
    @goal_instance.cheer_ons = @goal_instance.cheer_ons + 1
    @goal_instance.update_attributes(params[:goal_instance])

    respond_to do |format|
      format.html {redirect_to @goal_instance}
    end
  end

  def check
    puts 'cheeeeeeck milestone'
    @goal_instance = GoalInstance.find(params[:id])
    Milestone.update(params[:milestone_id],:is_complete => '1')
    milestone = @goal_instance.milestones.find(params[:milestone_id])

    if params[:complete] == (@goal_instance.end_date-@goal_instance.start_date).to_f
      @goal_instance.is_complete = '1'
      @goal_instance.update_attributes(params[:goal_instance])
    end
     respond_to do |format|
      format.html {redirect_to goal_instance_path(:complete => params[:complete].to_f + ((@goal_instance.end_date - @goal_instance.start_date) * (milestone.duration.to_f/params[:sum].to_f)))}
    end
  end
end

app/helpers/goal_instances_helper.rb
module GoalInstancesHelper
end

app/views/goal_instances/_form.html.erb
<%= form_for(@goal_instance) do |f| %>
  <% if @goal_instance.errors.any? %>
    <div class="alert alert-danger" >
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2><%= pluralize(@goal_instance.errors.count, "error") %> prohibited this goal_instance from being saved:</h2>

      <ul>
      <% @goal_instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />


  <div class="form-group">
    <h4>
      <span class="label label-success"><%= f.label :start_date %></span>
      <%= f.date_select :start_date %>
    </h4>
  </div>

  <div class="form-group">
    <h4>
      <span class="label label-success"><%= f.label :end_date %></span>
      <%= f.date_select :end_date %>
    </h4>
  </div>

  <% i = 1 %>

  <hr />

  <h3><b> Milestone Information </b></h3>

  <hr />
  
  <%= f.fields_for :milestones do |m| %>
    <div class="container pull-left">
      <div class="pull-left">
        <h4><span class="label label-primary">Milestone <%= i %> <%= m.label :description %> </span></h4>
        <%= m.text_area :description, rows:3, :class => "form-control" %>
      </div>

      <div class="pull-left" style="margin-left:30px;">
          <h4><span class="label label-primary">Milestone <%= i %> Weight</span></h4>
          <%= m.text_field :duration, columns:1, :class => "form-control" %>
      </div>

      <div class="actions">
        <%= m.hidden_field :is_complete, :value => "false" %>
      </div>
    </div>  

    <% i = i + 1 %>
  <%end%>
  
  <hr />
  <div class="actions">
    <%= f.hidden_field :is_complete, :value => "false" %>
    <%= f.hidden_field :cheer_ons, :value => "0" %>
    <%= f.hidden_field :goal_id, :value => params[:goal_id] %>

    <%= link_to raw('<i class="glyphicon glyphicon-chevron-left"></i> Back'), goal_instances_path, :class => "btn btn-primary" %>
    <%= f.submit 'Create Goal Instance', :class => "btn btn-success navbar-btn" %>
  </div>
<% end %>

app/views/goal_instances/_form1.html.erb
<%= form_for(@goal_instance) do |f| %>
  <% if @goal_instance.errors.any? %>
    <div class="alert alert-danger" >
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2><%= pluralize(@goal_instance.errors.count, "error") %> prohibited this goal_instance from being saved:</h2>

      <ul>
      <% @goal_instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h4>
      <span class="label label-primary"><%= f.label :start_date %></span>
      <%= f.date_select :start_date %>
    </h4>
  </div>

  <div class="form-group">
    <h4>
      <span class="label label-primary"><%= f.label :end_date %></span>
      <%= f.date_select :end_date %>
    </h4>
  </div>

  <div class="actions">
    <%= f.hidden_field :is_complete, :value => false %>

    <hr />
    <%= link_to raw('<i class="glyphicon glyphicon-chevron-left"></i> Back'), goal_instances_path, :class => "btn btn-primary" %>
    <%= f.submit 'Update Goal Instance', :class => "btn btn-success navbar-btn" %>
  </div>
<% end %>

app/views/goal_instances/edit.html.erb
<div class="container">
	<div class="pull-left" style="margin: 20px 20px 0px 0px;">
		<a href="#">
			<%= image_tag @goal_instance.goal.picture.url, :class => "img-thumbnail img-responsive", :width => "350px", :height => "350x" %>
		</a>
	</div>

	<div class="container">
		<h1><b><%= @goal_instance.goal.title %></b></h1>
		<hr />
		<h2><small><%= @goal_instance.goal.description %></small></h2>
		<hr />
	</div>	

	<%= render 'form1' %>

</div>

app/views/goal_instances/index.html.erb
<div class="container container-gi">

<% if params[:user_id] != nil && session['current_user'].to_s != params[:user_id].to_s %>
  <h2><%= "Goals pursued by " + User.find(params[:user_id]).first_name + " " + User.find(params[:user_id]).last_name%></h2>
  <br />
<%end%>

<% @goal_instances.each do |goal_instance| %>
  <li class="thumbnail">  
        <div class="container container-gi">
          <div class="row">
            <div class="col-sm-2">
              <%= image_tag goal_instance.goal.picture.url, :width => "120px", :height => "100px"%>
            </div>
            
            <div class="col-sm-8">
            <% unless goal_instance.goal.nil? then %> 
              <em><h4><%= link_to goal_instance.goal.title , goal_instance%></h4></em>
            <%end%>


            <div class="progress">
              <div class="progress-bar" role="progressbar" 
                  aria-valuenow="<% if (Date.today-goal_instance.start_date) > (goal_instance.end_date-goal_instance.start_date) then %>
                                      100%
                                 <%else%> <%=((Date.today-goal_instance.start_date).to_f/(goal_instance.end_date-goal_instance.start_date).to_f)*100%>%
                                 <%end%>" 
                  aria-valuemin="0" 
                  aria-valuemax= "100%" 
                  style="width:<% if (Date.today-goal_instance.start_date) > (goal_instance.end_date-goal_instance.start_date) then %>
                                      100%
                                 <%else%> <%=((Date.today-goal_instance.start_date).to_f/(goal_instance.end_date-goal_instance.start_date).to_f)*100%>%
                              <%end%>" 
              > 
                <%if (Date.today-goal_instance.start_date) > (goal_instance.end_date-goal_instance.start_date) then %>
                100% complete
                <%else%> 
                  <% if (((Date.today-goal_instance.start_date).to_f/(goal_instance.end_date-goal_instance.start_date).to_f)*100).round < 0 then %> 
                    0% complete
                  <% else %> <%=(((Date.today-goal_instance.start_date).to_f/(goal_instance.end_date-goal_instance.start_date).to_f)*100).round%>% complete
                  <% end %>
                <%end%>
              </div>
            </div>

            </div>
            
            <br />
            <br />
            
            <div class="col-sm-2">
              <% unless goal_instance.goal.nil? then %> 
                <span class="badge" class="pull-right"><%= goal_instance.cheer_ons%> Cheer Ons <i class="glyphicon glyphicon-heart"></i>  </span>
               <%end%> 
            </div>
            </div> 
          </div>
  </li>
<% end %>
</ul>
<br />

<!--  <%= button_to "my_button" %>
$(function(){
  $("#my-button").click(function(){
    $.post('/myroute');
  })
})-->

<%= will_paginate @goal_instances, renderer: BootstrapPagination::Rails, :class => "center-block" %>

</div>

app/views/goal_instances/new.html.erb
<div class="container">
	<% current_goal = Goal.find(params[:goal_id])%>
	<div class="pull-left" style="margin: 20px 20px 0px 0px;">
		<a href="#">
			<%= image_tag current_goal.picture.url, :class => "img-thumbnail img-responsive", :width => "350px", :height => "350x"  %>
		</a>
	</div>
	
	<div class="container">
		<h1><b><%= current_goal.title %></b></h1>
		<hr />
		<h2><small><%= current_goal.description %></small></h2>
		<hr />
		Created by <b><%= current_goal.user.first_name + " " + current_goal.user.last_name%></b>
	</div>	
	
	<%= render 'form' %>
</div>

app/views/goal_instances/show.html.erb
<div class="container">

<% if notice %>
<div class="alert alert-success" >
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<p id="notice"><%= notice %></p>
</div>
<% end %>

<% whole = (@goal_instance.end_date-@goal_instance.start_date).to_f %>
<% complete = 0 %>
        	
<div class="container">
	<div class="pull-left" style="margin: 20px 20px 0px 0px;">
		<a href="#">
			<%= image_tag @goal_instance.goal.picture.url, :class => "img-thumbnail img-responsive", :width => "350px", :height => "350x" %>
		</a>
	</div>


	<div class="container">
		<div class="pull-right" style="margin-top:10px;">
			<% if !@is_current_user_joined %>
				<%= link_to raw('Join <i class="glyphicon glyphicon-share-alt"></i>'), new_goal_instance_path(:goal_id => @goal_instance.goal.id), :class => "btn btn-lg btn-success"%>
			<%end%>
		</div>


		<h1><b><%= @goal_instance.goal.title %></b></h1>
		<hr />
		<h2><small><%= @goal_instance.goal.description %></small></h2>
		<hr />

		<div class="pull-left">
			<h4>
			<% if session[:current_user] == @goal_instance.user.id then %>
				You have <b class="label label-success"><%=@goal_instance.cheer_ons%> Cheer Ons</b> for this goal.
			<% else %> 
				<%=@goal_instance.user.first_name %> has <b class="label label-primary"><%=@goal_instance.cheer_ons%> Cheer Ons</b> for this goal.
			<%end%>
			</h4>
		</div>


		<div class="pull-right">
			<h4>
			<i class="glyphicon glyphicon-ok-sign"></i>
			<% if @goal_instance.start_date < Date.today %>
				Started 
				<a title=<%= @goal_instance.start_date%> style="color:inherit;">
				<%= distance_of_time_in_words_to_now(@goal_instance.start_date, include_seconds: true)%>
				</a> ago
			<% else %>
				<% if @goal_instance.start_date > Date.today %>
					Start in 
					<a title=<%= @goal_instance.start_date%> style="color:inherit;">
					<%= distance_of_time_in_words_to_now(@goal_instance.start_date, include_seconds: true)%>
					</a>
				<% else %>
					Started Today
				<% end %>
			<% end %>
			</h4>

			<h4>
			<i class="glyphicon glyphicon-ok-sign"></i>
			<% if @goal_instance.is_complete %>
				Completed 
				<a title=<%= @goal_instance.end_date%> style="color:inherit;">
				<%= time_ago_in_words(@goal_instance.end_date, include_seconds: true)%> 
				</a> ago
			<% else %>
				<% if @goal_instance.end_date < Date.today %>
					Was due 
					<a title=<%= @goal_instance.end_date%> style="color:inherit;">
					<%= distance_of_time_in_words_to_now(@goal_instance.end_date, include_seconds: true)%> 
					</a> ago
				<% elsif @goal_instance.end_date > Date.today %>
					End in 
					<a title=<%= @goal_instance.end_date%> style="color:inherit;">
					<%= distance_of_time_in_words_to_now(@goal_instance.end_date, include_seconds: true)%>
					</a>
				<% else %>
					To be completed by Today
				<% end %>
			<% end %>
			</h4>
		</div>

		<br />
		<br />
		<br />
		<br />

		<% if session[:current_user] != @goal_instance.user.id then %>
			<hr />
			<div class="pull-left">
				<%= button_to 'Cheer On', {:action => 'cheeron', remote: true }, :class => 'btn btn-success btn-lg', :method => :put%>
			</div>
			<div style="padding:2px 0 0 0; text-indent: 15px">
				<h4> <%= @goal_instance.user.first_name + ' ' + @goal_instance.user.last_name %> </h4>
			</div>	
		<% end %>
	</div>


	<hr />	

	<div class="container" class="pull-right">
	    <% sum = 0 %>
	    <% @milestones.each do |milestone| 
	    	sum = sum + milestone.duration.to_i 
	    end %>

	  	<div class="col-sm-7">
	  		<div class="row">
	  			<div class="col-sm-7">
	  				<h3>
		  			<% if session[:current_user] == @goal_instance.user.id then %>
		  				Your Milestones
		  			<%else%> 
		  				<%= @goal_instance.user.first_name %>'s Milestones
		  			<%end%>
	  				</h3>
	  			</div>
	  		</div>

	  		<br />

	  		<div class="row">
		        <div class="col-sm-2">
					Status
		        </div>
		        <div class="col-sm-6 text-center">
		        	Milestone Description
		        </div>
		        <div class="col-sm-3">
		        	Estimated Time
		        </div>
		        
	    	</div> 

	  		<hr />

	        <% @milestones.each do |milestone| %>
		        <div class="row">
			        <div class="col-sm-2">
						<% if session[:current_user] == @goal_instance.user.id then %>
							<% if !milestone.is_complete then %>
						        <%= button_to 'Incomplete', {:action => 'check', :milestone_id => milestone.id, :remote => true}, :class => 'btn btn-danger btn-sm', :method => :put%>
							<% elsif milestone.is_complete then %> 
						    	<button type="button" class="btn btn-success btn-sm">Complete</button>
						    		<% complete = complete + (@goal_instance.end_date - @goal_instance.start_date) * (milestone.duration.to_f/sum.to_f) %>
						     <%end%>
						<%else%>
							<% if !milestone.is_complete then %>
								<button type="button" class="btn btn-danger btn-sm">Incomplete</button>
							<% elsif milestone.is_complete then %> 
								<button type="button" class="btn btn-success btn-sm">Complete</button>
								<% complete = complete + (@goal_instance.end_date - @goal_instance.start_date) * (milestone.duration.to_f/sum.to_f) %>
							<%end%>
						<%end%>
			        </div>
			        <div class="col-sm-6 text-center">
			        	<b><%= milestone.description %></b>
			        </div>
			        <div class="col-sm-3">
			        	<b><%= "%.1f" % ((@goal_instance.end_date - @goal_instance.start_date) * (milestone.duration.to_f/sum.to_f)) %> days</b>
			        </div>
	    		</div> 
	    		<br />  
	    	<% end %>
		</div>

		<div class="col-sm-4">
			<% if complete == 0 then %>
				<img src="<%= Gchart.pie(:size => '400x250', :data => [0,whole], :labels => ["","Incomplete"])%>"/>
			<% elsif whole == complete then %>
				<img src="<%= Gchart.pie(:size => '400x250', :data => [whole,0], :labels => ["Complete"])%>" />
			<% else %>
				<img src="<%= Gchart.pie(:size => '400x250', :data => [complete,whole - complete], :labels =>["Complete","Incomplete"])%>"/>
			<%end%>
		</div>
	</div>

	<% if whole == complete then %>
	 <div class="alert alert-success" >
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<p id="notice">Congratulations! You completed this goal !</p>
	</div>
	<%end%>

	<hr />

	<div class="pull-left">
		<%= link_to raw('<i class="glyphicon glyphicon-chevron-left"></i> Back'), goal_instances_path(:user_id => @goal_instance.user.id), :class => "btn btn-primary" %>
		<%if User.find(session[:current_user]) == @goal_instance.user %>
			<%=link_to raw('<i class="glyphicon glyphicon-edit"></i> Edit'), edit_goal_instance_path(@goal_instance), :class => "btn btn-success" %>
		<%end%> 	
	</div>
	<%if User.find(session[:current_user]) == @goal_instance.user %>
	<div class="pull-right">
		<%=button_to 'Delete', @goal_instance, method: :delete, html_options: {confirm: 'Are you sure?'}, :class => "btn btn-default" %>	
	</div>
	<%end%>
</div>